# Copyright 2021 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

# system config
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset config
dataset: 'imagenet'
data_dir: './imagenet/'

shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# Augmentation config
image_resize: 256
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bilinear'

## none
# crop_pct: 1.0
# color_jitter: 0.0
# re_prob: 0.0

crop_pct: 0.875
color_jitter: [0.4, 0.4, 0.4]
re_prob: 1.0

# re_value: 'random'

# auto_augment: 'autoaug-mstd0.5'
# mixup: 0.5
# cutmix: 1.0
# cutmix_prob: 1.0

# model config
model: 'mobile_vit_x_small'
num_classes: 1000
pretrained: False
ckpt_path: ''
# ckpt_path: 'ckpt/mobile_vit_small_best.ckpt'
keep_checkpoint_max: 10
ckpt_save_dir: './ckpt/'
epoch_size: 450
dataset_sink_mode: True
amp_level: 'O3'

# loss config
loss: 'ce'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'warmup_cosine_decay'
min_lr: 0.000002
lr: 0.002
warmup_epochs: 20
decay_epochs: 430

# optimizer config
opt: 'adamw'
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 0.01
use_nesterov: False
dynamic_loss_scale: True
loss_scale: 1024